-- 1. Insert Muscle Groups
INSERT INTO muscle_groups (id, name, image) VALUES
                                                (1, 'Chest', 'https://drive.google.com/uc?id=1J4ZrnHY8Coi4Jqd_IKErNuxOKWn9yVO2'),
                                                (2, 'Back', 'https://drive.google.com/uc?id=1W7D7mdGuplJeru-0UzJGowO-RaJr4Xz7'),
                                                (3, 'Shoulder', 'https://drive.google.com/uc?id=1np00rXyMBjua5wXdofCMxFccPfaixEmQ'),
                                                (4, 'Legs', 'https://drive.google.com/uc?id=1U9Ztw3MCVmDFnHMbJdP9qsIyTm00hzwf'),
                                                (5, 'Arms', 'https://drive.google.com/uc?id=1BRK3udwDfBPl-IbXCy1m3cHHbhOuebVd'),
                                                (6, 'Core', 'https://drive.google.com/uc?id=1Ur8z6G8OJJQNFOTtzTz_yKQb9fD9YxKc');

-- 2. Insert Muscles
INSERT INTO muscles (id, muscle_group_id, name) VALUES
                                                    (1, 1, 'Pectoralis major'),
                                                    (2, 1, 'Pectoralis minor'),
                                                    (3, 2, 'Latissimus dorsi'),
                                                    (4, 2, 'Trapezius'),
                                                    (5, 2, 'Spinal erectors (lumbar)'),
                                                    (6, 2, 'Teres major'),
                                                    (7, 2, 'Serratus anterior'), (8, 2, 'Infraspinatus'), (9, 2, 'Rhomboids'),
                                                    (10, 3, 'Quadriceps'), (11, 3, 'Adductors'), (12, 3, 'Abductors'),
                                                    (13, 3, 'Soleus'), (14, 3, 'Hamstrings'), (15, 3, 'Gluteus maximus'),
                                                    (16, 3, 'Gluteus medius'), (17, 3, 'Tibialis anterior'), (18, 3, 'Gastrocnemius'),
                                                    (19, 4, 'Anterior deltoid'), (20, 4, 'Lateral deltoid'), (21, 4, 'Posterior deltoid'),
                                                    (22, 5, 'Biceps brachii'), (23, 5, 'Triceps brachii'), (24, 5, 'Brachialis'),
                                                    (25, 5, 'Brachioradialis'), (26, 6, 'Rectus abdominis'), (27, 6, 'Obliques'),
                                                    (28, 6, 'Transverse abdominis');

-- 3. Insert Base Exercises
INSERT INTO exercises (id, name, image , muscle_group_id) VALUES
                                                      (1, 'Bench Press', 'https://drive.google.com/uc?id=1nsGz08zBI4U6057Bk4DdYXJE4MoutVq2', 1),
                                                      (2, 'Incline Bench Press', 'https://drive.google.com/uc?id=1h-Kbj7owjoV1DtXD-pS8Dd1p1dvdhHI5', 1),
                                                      (3, 'Dumbbell Flyes', 'https://drive.usercontent.google.com/download?id=1vvHWOccDhsQQ7CjJiqED7xr45S_16-rJ&authuser=0', 1),
                                                      (4, 'Cable Crossovers', '', 1),
                                                      (5, 'Dumbbell Pullover', 'https://drive.usercontent.google.com/download?id=1v_-gMAnBW_h_QuTnHromBiUnMfWoaaOT&authuser=0', 1),
                                                      (6, 'Chest Dips', '', 1),
                                                      (7, 'Push-Ups', 'https://drive.google.com/uc?id=1HdVrOHC1bh8elb_anNp_5TJ1GEIYYHb2', 1),

                                                      (8, 'Deadlift', '', 2),
                                                      (9, 'Barbell Row', '', 2),
                                                      (10, 'Seated Cable Row', '', 2),
                                                      (11, 'Pull-Ups', '', 2),
                                                      (12, 'Lat Pulldown', '', 2),
                                                      (13, 'Shrugs', '', 2),

                                                      (14, 'Squats', '', 3),
                                                      (15, 'Leg Extension', '', 3),
                                                      (16, 'Leg Curl', '', 3),
                                                      (17, 'Hip Thrust', '', 3),
                                                      (18, 'Glute Kickback', '', 3),
                                                      (19, 'Lunges', '', 3),
                                                      (20, 'Leg Press', '', 3),
                                                      (21, 'Hack Squat', '', 3),
                                                      (22, 'Box Step-Ups', '', 3),

                                                      (23, 'Overhead Press', '', 4),
                                                      (24, 'Arnold Press', '', 4),
                                                      (25, 'Front Raises', '',4),
                                                      (26, 'Lateral Raises', '', 4),
                                                      (27, 'Upright Row', '', 4),
                                                      (28, 'Shoulder Flexion', '', 4),
                                                      (29, 'Rear Delt Raises', '', 4),

                                                      (30, 'Biceps Curl', '', 5),
                                                      (31, 'Preacher Curl', '', 5),
                                                      (32, 'Hammer Curl', '', 5),
                                                      (33, 'Triceps Extension', '', 5),
                                                      (34, 'Skull Crushers', '', 5),
                                                      (35, 'Diamond Push-Ups', '', 5),
                                                      (36, 'Triceps Dips', '', 5),

                                                      (37, 'Plank', '', 6),
                                                      (38, 'Dead Bug', '', 6),
                                                      (39, 'Bird Dog', '', 6),
                                                      (40, 'Mountain Climbers', '', 6),
                                                      (41, 'Pallof Press', '', 6),
                                                      (42, 'Farmer’s Walk', '', 6),
                                                      (43, 'Glute Bridge', '', 6),
                                                      (44, 'Back Extension', '', 6),
                                                      (45, 'Russian Twists', '', 6),
                                                      (46, 'Hollow Hold', '', 6);

-- 4. Insert Exercise-Muscle Relationships
INSERT INTO exercises_muscles (exercise_id, muscle_id, role) VALUES
                                                                 (1, 1, 'primary'), (1, 23, 'secondary'), (1, 20, 'secondary'),
                                                                 (2, 1, 'primary'), (2, 20, 'secondary'), (3, 1, 'primary'),
                                                                 (4, 1, 'primary'), (5, 1, 'secondary'), (5, 3, 'secondary'),
                                                                 (6, 1, 'primary'), (6, 23, 'secondary'), (7, 1, 'primary'), (7, 23, 'secondary'),
                                                                 (8, 5, 'primary'), (8, 15, 'primary'), (8, 14, 'secondary'),
                                                                 (9, 3, 'primary'), (9, 9, 'secondary'), (9, 4, 'secondary'), (9, 22, 'secondary'),
                                                                 (10, 3, 'primary'), (10, 9, 'secondary'), (10, 4, 'secondary'), (10, 22, 'secondary'),
                                                                 (11, 3, 'primary'), (11, 6, 'secondary'), (11, 22, 'secondary'), (11, 24, 'secondary'),
                                                                 (12, 3, 'primary'), (12, 6, 'secondary'), (12, 22, 'secondary'),
                                                                 (13, 4, 'primary'), (13, 5, 'stabilizer'),
                                                                 (14, 10, 'primary'), (14, 15, 'secondary'), (14, 14, 'secondary'), (14, 11, 'stabilizer'), (14, 16, 'stabilizer'),
                                                                 (15, 10, 'primary'), (16, 14, 'primary'),
                                                                 (17, 15, 'primary'), (17, 14, 'secondary'), (17, 16, 'secondary'),
                                                                 (18, 15, 'primary'), (18, 16, 'secondary'),
                                                                 (19, 10, 'primary'), (19, 15, 'secondary'), (19, 14, 'secondary'), (19, 16, 'stabilizer'),
                                                                 (20, 10, 'primary'), (20, 15, 'secondary'), (20, 14, 'secondary'),
                                                                 (21, 10, 'primary'), (21, 15, 'secondary'), (21, 14, 'secondary'),
                                                                 (22, 10, 'primary'), (22, 15, 'secondary'), (22, 14, 'secondary'), (22, 16, 'stabilizer'),
                                                                 (23, 19, 'primary'), (23, 20, 'secondary'), (23, 23, 'secondary'),
                                                                 (24, 19, 'primary'), (24, 20, 'secondary'), (24, 23, 'secondary'),
                                                                 (25, 19, 'primary'), (26, 20, 'primary'), (26, 4, 'secondary'),
                                                                 (27, 20, 'primary'), (27, 4, 'secondary'), (27, 22, 'secondary'),
                                                                 (28, 19, 'primary'), (29, 21, 'primary'), (29, 4, 'secondary'),
                                                                 (30, 22, 'primary'), (30, 24, 'secondary'), (30, 25, 'secondary'),
                                                                 (31, 22, 'primary'), (31, 24, 'secondary'),
                                                                 (32, 25, 'primary'), (32, 24, 'secondary'), (32, 22, 'secondary'),
                                                                 (33, 23, 'primary'), (34, 23, 'primary'),
                                                                 (35, 23, 'primary'), (35, 22, 'secondary'),
                                                                 (36, 23, 'primary'), (36, 22, 'secondary'),
                                                                 (37, 28, 'primary'), (37, 26, 'secondary'), (37, 27, 'secondary'),
                                                                 (38, 28, 'primary'), (38, 26, 'secondary'),
                                                                 (39, 5, 'secondary'), (39, 28, 'secondary'),
                                                                 (40, 26, 'primary'), (40, 27, 'secondary'),
                                                                 (41, 27, 'primary'), (41, 28, 'secondary'),
                                                                 (42, 28, 'primary'), (42, 27, 'secondary'),
                                                                 (43, 15, 'primary'), (43, 5, 'secondary'),
                                                                 (44, 5, 'primary'), (44, 15, 'secondary'),
                                                                 (45, 27, 'primary'), (45, 26, 'secondary'),
                                                                 (46, 26, 'primary'), (46, 28, 'secondary');

-- 5. Insert Exercise Variants
INSERT INTO exercises_variants (id, exercise_id, name) VALUES
                                                           (1, 1, 'Dumbbell Bench Press'),
                                                           (2, 2, 'Incline Dumbbell Bench Press'),
                                                           (3, 3, 'Incline Bench Flyes'),
                                                           (4, 3, 'Flat Bench Flyes'),
                                                           (5, 7, 'Plyometric Push-Ups'),
                                                           (6, 8, 'Sumo Deadlift'),
                                                           (7, 8, 'Dumbbell Deadlift'),
                                                           (8, 9, '3-Point Dumbbell Row'),
                                                           (9, 10, 'Single-Arm Cable Row'),
                                                           (10, 10, 'Wide-Grip Cable Row'),
                                                           (11, 10, 'Close-Grip Cable Row'),

                                                           (12, 11, 'Underhand Pull-Ups'),
                                                           (13, 11, 'Neutral-Grip Pull-Ups'),
                                                           (14, 11, 'Weighted Pull-Ups'),

                                                           (15, 12, 'Wide-Grip Lat Pulldown'),
                                                           (16, 12, 'Close-Grip Lat Pulldown'),
                                                           (17, 12, 'Single-Arm Lat Pulldown'),

                                                           (18, 13, 'Dumbbell Shrugs'),

                                                           (19, 14, 'Barbell Squat'),
                                                           (20, 14, 'Dumbbell Squat'),
                                                           (21, 14, 'Sumo Squat'),
                                                           (22, 14, 'Bulgarian Split Squat'),
                                                           (23, 16, 'Lying Leg Curl'),
                                                           (24, 16, 'Seated Leg Curl'),
                                                           (25, 17, 'Machine Hip Thrust'),
                                                           (26, 17, 'Barbell Hip Thrust'),
                                                           (27, 17, 'Plate Hip Thrust'),
                                                           (28, 18, 'Cable Glute Kickback'),
                                                           (29, 18, 'Machine Glute Kickback'),
                                                           (30, 19, 'Barbell Lunges'),
                                                           (31, 19, 'Dumbbell Lunges'),
                                                           (32, 22, 'Weighted Box Step-Ups'),
                                                           (33, 22, 'Box Jump'),

                                                           (34, 23, 'Dumbbell Shoulder Press'),
                                                           (35, 25, 'Dumbbell Front Raises'),
                                                           (36, 25, 'Low Cable Front Raises'),
                                                           (37, 25, 'Plate Front Raises'),
                                                           (38, 26, 'Dumbbell Lateral Raises'),
                                                           (39, 26, 'Low Cable Lateral Raises'),
                                                           (40, 26, 'Machine Lateral Raises'),
                                                           (41, 29, 'Dumbbell Rear Delt Raises'),
                                                           (42, 29, 'Low Cable Rear Delt Raises'),
                                                           (43, 29, 'Machine Rear Delt Raises'),

                                                           (44, 30, 'Barbell Biceps Curl'),
                                                           (45, 30, 'Dumbbell Biceps Curl'),
                                                           (46, 30, 'Low Cable Biceps Curl'),
                                                           (47, 30, 'Machine Biceps Curl'),
                                                           (48, 31, 'Dumbbell Preacher Curl'),
                                                           (49, 32, 'Low Cable Hammer Curl'),
                                                           (50, 33, 'Machine Triceps Extension'),
                                                           (51, 33, 'Plate Triceps Extension'),
                                                           (52, 33, 'Dumbbell Triceps Extension'),
                                                           (53, 33, 'High Cable Triceps Extension'),
                                                           (54, 34, 'EZ-Bar Skull Crusher'),
                                                           (55, 34, 'Dumbbell Skull Crusher'),
                                                           (56, 36, 'Parallel Bar Triceps Dips'),
                                                           (57, 36, 'Bench Triceps Dips'),

                                                           (58, 37, 'Front Plank'),
                                                           (59, 37, 'Side Plank');
