-- 1. Insert Muscle Groups
INSERT INTO muscle_groups (id, name, image) VALUES
                                                (1, 'Chest', ''), (2, 'Back', ''), (3, 'Shoulder', ''),
                                                (4, 'Legs', ''), (5, 'Arms', ''), (6, 'Core', '');

-- 2. Insert Muscles
INSERT INTO muscles (id, muscle_group_id, name) VALUES
                                                    (1, 1, 'Pectoralis major'), (2, 1, 'Pectoralis minor'), (3, 2, 'Latissimus dorsi'),
                                                    (4, 2, 'Trapezius'), (5, 2, 'Spinal erectors (lumbar)'), (6, 2, 'Teres major'),
                                                    (7, 2, 'Serratus anterior'), (8, 2, 'Infraspinatus'), (9, 2, 'Rhomboids'),
                                                    (10, 3, 'Quadriceps'), (11, 3, 'Adductors'), (12, 3, 'Abductors'),
                                                    (13, 3, 'Soleus'), (14, 3, 'Hamstrings'), (15, 3, 'Gluteus maximus'),
                                                    (16, 3, 'Gluteus medius'), (17, 3, 'Tibialis anterior'), (18, 3, 'Gastrocnemius'),
                                                    (19, 4, 'Anterior deltoid'), (20, 4, 'Lateral deltoid'), (21, 4, 'Posterior deltoid'),
                                                    (22, 5, 'Biceps brachii'), (23, 5, 'Triceps brachii'), (24, 5, 'Brachialis'),
                                                    (25, 5, 'Brachioradialis'), (26, 6, 'Rectus abdominis'), (27, 6, 'Obliques'),
                                                    (28, 6, 'Transverse abdominis');

-- 3. Insert Base Exercises
INSERT INTO exercises (id, name, muscle_group_id) VALUES
                                                      (1, 'Bench press', 1), (2, 'Incline bench press', 1), (3, 'Flyes', 1),
                                                      (4, 'Cable crossover', 1), (5, 'Pullover', 1), (6, 'Dips', 1),
                                                      (7, 'Push-ups', 1), (8, 'Deadlift', 2), (9, 'Barbell row', 2),
                                                      (10, 'Seated cable row', 2), (11, 'Pull-ups', 2), (12, 'Lat pulldown', 2),
                                                      (13, 'Shrugs', 2), (14, 'Squats', 3), (15, 'Quad extension', 3),
                                                      (16, 'Leg curl', 3), (17, 'Hip thrust', 3), (18, 'Glute kickback', 3),
                                                      (19, 'Lunges', 3), (20, 'Leg press', 3), (21, 'Hack squat', 3),
                                                      (22, 'Box step-ups', 3), (23, 'Military press', 4), (24, 'Arnold press', 4),
                                                      (25, 'Front raises', 4), (26, 'Lateral raises', 4), (27, 'Upright row', 4),
                                                      (28, 'Shoulder flexions', 4), (29, 'Rear delt raises', 4), (30, 'Bicep curl', 5),
                                                      (31, 'Preacher curl', 5), (32, 'Hammer curl', 5), (33, 'Tricep extension', 5),
                                                      (34, 'Skull crusher', 5), (35, 'Diamond push-ups', 5), (36, 'Dips', 5),
                                                      (37, 'Plank', 6), (38, 'Dead bug', 6), (39, 'Bird dog', 6),
                                                      (40, 'Mountain climber', 6), (41, 'Pallof press', 6), (42, 'Farmer walk', 6),
                                                      (43, 'Glute bridge', 6), (44, 'Back extension', 6), (45, 'Russian twists', 6),
                                                      (46, 'Hollow hold', 6);

-- 4. Insert Exercise-Muscle Relationships
INSERT INTO exercises_muscles (exercise_id, muscle_id, role) VALUES
                                                                 (1, 1, 'primary'), (1, 23, 'secondary'), (1, 20, 'secondary'),
                                                                 (2, 1, 'primary'), (2, 20, 'secondary'), (3, 1, 'primary'),
                                                                 (4, 1, 'primary'), (5, 1, 'secondary'), (5, 3, 'secondary'),
                                                                 (6, 1, 'primary'), (6, 23, 'secondary'), (7, 1, 'primary'), (7, 23, 'secondary'),
                                                                 (8, 5, 'primary'), (8, 15, 'primary'), (8, 14, 'secondary'),
                                                                 (9, 3, 'primary'), (9, 9, 'secondary'), (9, 4, 'secondary'), (9, 22, 'secondary'),
                                                                 (10, 3, 'primary'), (10, 9, 'secondary'), (10, 4, 'secondary'), (10, 22, 'secondary'),
                                                                 (11, 3, 'primary'), (11, 6, 'secondary'), (11, 22, 'secondary'), (11, 24, 'secondary'),
                                                                 (12, 3, 'primary'), (12, 6, 'secondary'), (12, 22, 'secondary'),
                                                                 (13, 4, 'primary'), (13, 5, 'stabilizer'),
                                                                 (14, 10, 'primary'), (14, 15, 'secondary'), (14, 14, 'secondary'), (14, 11, 'stabilizer'), (14, 16, 'stabilizer'),
                                                                 (15, 10, 'primary'), (16, 14, 'primary'),
                                                                 (17, 15, 'primary'), (17, 14, 'secondary'), (17, 16, 'secondary'),
                                                                 (18, 15, 'primary'), (18, 16, 'secondary'),
                                                                 (19, 10, 'primary'), (19, 15, 'secondary'), (19, 14, 'secondary'), (19, 16, 'stabilizer'),
                                                                 (20, 10, 'primary'), (20, 15, 'secondary'), (20, 14, 'secondary'),
                                                                 (21, 10, 'primary'), (21, 15, 'secondary'), (21, 14, 'secondary'),
                                                                 (22, 10, 'primary'), (22, 15, 'secondary'), (22, 14, 'secondary'), (22, 16, 'stabilizer'),
                                                                 (23, 19, 'primary'), (23, 20, 'secondary'), (23, 23, 'secondary'),
                                                                 (24, 19, 'primary'), (24, 20, 'secondary'), (24, 23, 'secondary'),
                                                                 (25, 19, 'primary'), (26, 20, 'primary'), (26, 4, 'secondary'),
                                                                 (27, 20, 'primary'), (27, 4, 'secondary'), (27, 22, 'secondary'),
                                                                 (28, 19, 'primary'), (29, 21, 'primary'), (29, 4, 'secondary'),
                                                                 (30, 22, 'primary'), (30, 24, 'secondary'), (30, 25, 'secondary'),
                                                                 (31, 22, 'primary'), (31, 24, 'secondary'),
                                                                 (32, 25, 'primary'), (32, 24, 'secondary'), (32, 22, 'secondary'),
                                                                 (33, 23, 'primary'), (34, 23, 'primary'),
                                                                 (35, 23, 'primary'), (35, 22, 'secondary'),
                                                                 (36, 23, 'primary'), (36, 22, 'secondary'),
                                                                 (37, 28, 'primary'), (37, 26, 'secondary'), (37, 27, 'secondary'),
                                                                 (38, 28, 'primary'), (38, 26, 'secondary'),
                                                                 (39, 5, 'secondary'), (39, 28, 'secondary'),
                                                                 (40, 26, 'primary'), (40, 27, 'secondary'),
                                                                 (41, 27, 'primary'), (41, 28, 'secondary'),
                                                                 (42, 28, 'primary'), (42, 27, 'secondary'),
                                                                 (43, 15, 'primary'), (43, 5, 'secondary'),
                                                                 (44, 5, 'primary'), (44, 15, 'secondary'),
                                                                 (45, 27, 'primary'), (45, 26, 'secondary'),
                                                                 (46, 26, 'primary'), (46, 28, 'secondary');

-- 5. Insert Exercise Variants
INSERT INTO exercises_variants (id, exercise_id, name) VALUES
                                                           (1, 1, 'Dumbbell bench press'), (2, 2, 'Incline dumbbell bench press'),
                                                           (3, 3, 'Incline bench flyes'), (4, 3, 'Flat bench flyes'),
                                                           (5, 7, 'Plyometric push-ups'), (6, 8, 'Sumo deadlift'),
                                                           (7, 8, 'Dumbbell deadlift'), (8, 9, 'Dumbbell row (3-point support)'),
                                                           (9, 10, 'Unilateral cable row'), (10, 10, 'Wide-grip cable row'),
                                                           (11, 11, 'Narrow-grip cable row'), (12, 12, 'Supinated pull-ups'),
                                                           (13, 13, 'Neutral-grip pull-ups'), (14, 14, 'Weighted pull-ups'),
                                                           (15, 15, 'Wide-grip pulldown'), (16, 16, 'Narrow-grip pulldown'),
                                                           (17, 17, 'Unilateral pulldown'), (18, 18, 'Dumbbell shrugs'),
                                                           (19, 14, 'Barbell squat'), (20, 14, 'Dumbbell squat'),
                                                           (21, 14, 'Sumo squat'), (22, 14, 'Bulgarian split squat'),
                                                           (23, 16, 'Lying leg curl'), (24, 16, 'Seated leg curl'),
                                                           (25, 17, 'Machine hip thrust'), (26, 17, 'Barbell hip thrust'),
                                                           (27, 17, 'Plate hip thrust'), (28, 18, 'Cable glute kickback'),
                                                           (29, 18, 'Machine glute kickback'), (30, 19, 'Barbell lunges'),
                                                           (31, 19, 'Dumbbell lunges'), (32, 22, 'Weighted box step-ups'),
                                                           (33, 22, 'Box jump'), (34, 23, 'Dumbbell shoulder press'),
                                                           (35, 25, 'Dumbbell front raises'), (36, 25, 'Low cable front raises'),
                                                           (37, 25, 'Plate front raises'), (38, 26, 'Dumbbell lateral raises'),
                                                           (39, 26, 'Low cable lateral raises'), (40, 26, 'Machine lateral raises'),
                                                           (41, 29, 'Dumbbell rear delt raises'), (42, 29, 'Low cable rear delt raises'),
                                                           (43, 29, 'Machine rear delt raises'), (44, 30, 'Barbell bicep curl'),
                                                           (45, 30, 'Dumbbell bicep curl'), (46, 30, 'Low cable bicep curl'),
                                                           (47, 30, 'Machine bicep curl'), (48, 31, 'Dumbbell preacher curl'),
                                                           (49, 32, 'Low cable hammer curl'), (50, 33, 'Machine tricep extension'),
                                                           (51, 33, 'Plate tricep extension'), (52, 33, 'Dumbbell tricep extension'),
                                                           (53, 33, 'High cable tricep extension'), (54, 34, 'EZ-bar skull crusher'),
                                                           (55, 34, 'Dumbbell skull crusher'), (56, 36, 'Parallel bar dips'),
                                                           (57, 36, 'Bench dips'), (58, 37, 'Front plank'),
                                                           (59, 37, 'Side plank');
