-- 1. Insertar Grupos Musculares
INSERT INTO muscle_groups (id, name, image) VALUES
                                                (1, 'Pecho', ''), (2, 'Espalda', ''), (3, 'Hombro', ''),
                                                (4, 'Piernas', ''), (5, 'Brazos', ''), (6, 'Core', '');

-- 2. Insertar Músculos
INSERT INTO muscles (id, muscle_group_id, name) VALUES
                                                    (1, 1, 'Pectoral mayor'), (2, 1, 'Pectoral menor'), (3, 2, 'Dorsal ancho'),
                                                    (4, 2, 'Trapecio'), (5, 2, 'Erectores espinales (lumbar)'), (6, 2, 'Redondo mayor'),
                                                    (7, 2, 'Serrato anterior'), (8, 2, 'Infraespinoso'), (9, 2, 'Romboides'),
                                                    (10, 3, 'Cuádriceps'), (11, 3, 'Aductores'), (12, 3, 'Abductores'),
                                                    (13, 3, 'Soleo'), (14, 3, 'Isquitibiales'), (15, 3, 'Glúteo mayor'),
                                                    (16, 3, 'Gluteo medio'), (17, 3, 'Tibial anterior'), (18, 3, 'Gemelos'),
                                                    (19, 4, 'Deltoides anterior'), (20, 4, 'Deltoides lateral'), (21, 4, 'Deltoides posterior'),
                                                    (22, 5, 'Bíceps braquial'), (23, 5, 'Tríceps braquial'), (24, 5, 'Braquial'),
                                                    (25, 5, 'Braquiorradial'), (26, 6, 'Recto abdominal'), (27, 6, 'Oblicuos'),
                                                    (28, 6, 'Transverso abdominal');

-- 3. Insertar Ejercicios Base
INSERT INTO exercises (id, name, muscle_group_id) VALUES
                                                      (1, 'Press banca', 1), (2, 'Press banca inclinado', 1), (3, 'Aperturas', 1),
                                                      (4, 'Cruce poleas', 1), (5, 'Pull over', 1), (6, 'Fondos', 1),
                                                      (7, 'Flexiones', 1), (8, 'Peso muerto', 2), (9, 'Remo barra', 2),
                                                      (10, 'Remo sentado polea', 2), (11, 'Dominadas', 2), (12, 'Tracciones polea alta', 2),
                                                      (13, 'Encogimientos', 2), (14, 'Sentadillas', 3), (15, 'Extensión cuádriceps', 3),
                                                      (16, 'Curl femoral', 3),
                                                      (17, 'Hip thrust', 3),
                                                      (18, 'Patada glúteo', 3),
                                                      (19, 'Zancadas', 3),
                                                      (20, 'Prensa', 3),
                                                      (21, 'Hack squat', 3),
                                                      (22, 'Subidas al box', 3),
                                                      (23, 'Press militar', 4),
                                                      (24, 'Press arnold', 4),
                                                      (25, 'Elevaciones frontales', 4),
                                                      (26, 'Elevaciones laterales', 4),
                                                      (27, 'Remo vertical', 4),
                                                      (28, 'Flexiones de hombro', 4),
                                                      (29, 'Elevaciones posteriores', 4),
                                                      (30, 'Curl bíceps', 5),
                                                      (31, 'Curl bíceps banco scott', 5),
                                                      (32, 'Curl martillo', 5),
                                                      (33, 'Extensión tríceps', 5),
                                                      (34, 'Press francés', 5), (35, 'Flexiones diamante', 5), (36, 'Fondos', 5),
                                                      (37, 'Plancha', 6), (38, 'Dead bug', 6), (39, 'Bird dog', 6),
                                                      (40, 'Escalador', 6), (41, 'Press Pallof', 6), (42, 'Farmer walk', 6),
                                                      (43, 'Puente de glúteos', 6), (44, 'Back extension', 6), (45, 'Russian twists', 6),
                                                      (46, 'Hollow hold', 6);

-- 4. Insertar Relaciones Exercises-Muscles
INSERT INTO exercises_muscles (exercise_id, muscle_id, role) VALUES
                                                                 (1, 1, 'primary'), (1, 23, 'secondary'), (1, 20, 'secondary'),
                                                                 (2, 1, 'primary'), (2, 20, 'secondary'), (3, 1, 'primary'),
                                                                 (4, 1, 'primary'), (5, 1, 'secondary'), (5, 3, 'secondary'),
                                                                 (6, 1, 'primary'), (6, 23, 'secondary'), (7, 1, 'primary'), (7, 23, 'secondary'),
                                                                 (8, 5, 'primary'), (8, 15, 'primary'), (8, 14, 'secondary'),
                                                                 (9, 3, 'primary'), (9, 9, 'secondary'), (9, 4, 'secondary'), (9, 22, 'secondary'),
                                                                 (10, 3, 'primary'), (10, 9, 'secondary'), (10, 4, 'secondary'), (10, 22, 'secondary'),
                                                                 (11, 3, 'primary'), (11, 6, 'secondary'), (11, 22, 'secondary'), (11, 24, 'secondary'),
                                                                 (12, 3, 'primary'), (12, 6, 'secondary'), (12, 22, 'secondary'),
                                                                 (13, 4, 'primary'), (13, 5, 'stabilizer'),
                                                                 (14, 10, 'primary'), (14, 15, 'secondary'), (14, 14, 'secondary'), (14, 11, 'stabilizer'), (14, 16, 'stabilizer'),
                                                                 (15, 10, 'primary'), (16, 14, 'primary'),
                                                                 (17, 15, 'primary'), (17, 14, 'secondary'), (17, 16, 'secondary'),
                                                                 (18, 15, 'primary'), (18, 16, 'secondary'),
                                                                 (19, 10, 'primary'), (19, 15, 'secondary'), (19, 14, 'secondary'), (19, 16, 'stabilizer'),
                                                                 (20, 10, 'primary'), (20, 15, 'secondary'), (20, 14, 'secondary'),
                                                                 (21, 10, 'primary'), (21, 15, 'secondary'), (21, 14, 'secondary'),
                                                                 (22, 10, 'primary'), (22, 15, 'secondary'), (22, 14, 'secondary'), (22, 16, 'stabilizer'),
                                                                 (23, 19, 'primary'), (23, 20, 'secondary'), (23, 23, 'secondary'),
                                                                 (24, 19, 'primary'), (24, 20, 'secondary'), (24, 23, 'secondary'),
                                                                 (25, 19, 'primary'), (26, 20, 'primary'), (26, 4, 'secondary'),
                                                                 (27, 20, 'primary'), (27, 4, 'secondary'), (27, 22, 'secondary'),
                                                                 (28, 19, 'primary'), (29, 21, 'primary'), (29, 4, 'secondary'),
                                                                 (30, 22, 'primary'), (30, 24, 'secondary'), (30, 25, 'secondary'),
                                                                 (31, 22, 'primary'), (31, 24, 'secondary'),
                                                                 (32, 25, 'primary'), (32, 24, 'secondary'), (32, 22, 'secondary'),
                                                                 (33, 23, 'primary'), (34, 23, 'primary'),
                                                                 (35, 23, 'primary'), (35, 22, 'secondary'),
                                                                 (36, 23, 'primary'), (36, 22, 'secondary'),
                                                                 (37, 28, 'primary'), (37, 26, 'secondary'), (37, 27, 'secondary'),
                                                                 (38, 28, 'primary'), (38, 26, 'secondary'),
                                                                 (39, 5, 'secondary'), (39, 28, 'secondary'),
                                                                 (40, 26, 'primary'), (40, 27, 'secondary'),
                                                                 (41, 27, 'primary'), (41, 28, 'secondary'),
                                                                 (42, 28, 'primary'), (42, 27, 'secondary'),
                                                                 (43, 15, 'primary'), (43, 5, 'secondary'),
                                                                 (44, 5, 'primary'), (44, 15, 'secondary'),
                                                                 (45, 27, 'primary'), (45, 26, 'secondary'),
                                                                 (46, 26, 'primary'), (46, 28, 'secondary');

-- 5. Insertar Exercises Variants
INSERT INTO exercises_variants (id, exercise_id, name) VALUES
                                                           (1, 1, 'Press banca mancuerna'), (2, 2, 'Press banca inclinado mancuera'),
                                                           (3, 3, 'Aperturas en banco inclinado'), (4, 3, 'Aperturas en banco horizontal'),
                                                           (5, 7, 'Flexiones pliométricas'), (6, 8, 'Peso muerto sumo'),
                                                           (7, 8, 'Peso muerto mancuernas'), (8, 9, 'Remo mancuernas (3 apoyos)'),
                                                           (9, 10, 'Remo polea unilarteral'), (10, 10, 'Remo polea agarre ancho'),
                                                           (11, 11, 'Remo polea agarre estrecho'), (12, 12, 'Dominadas supinas'),
                                                           (13, 13, 'Dominadas neutras'), (14, 14, 'Dominadas con lastre'),
                                                           (15, 15, 'Tracciones agarre ancho'), (16, 16, 'Tracciones agarre estrecho'),
                                                           (17, 17, 'Tracciones unilaterales'), (18, 18, 'Encogimientos con mancuernas'),
                                                           (19, 14, 'Sentadillas con barra'), (20, 14, 'Sentadillas con mancuerna'),
                                                           (21, 14, 'Sentadilla sumo'), (22, 14, 'Sentadilla búlgara'),
                                                           (23, 16, 'Curl femoral tumbado'), (24, 16, 'Curl femoral sentado'),
                                                           (25, 17, 'Hip thrust maquina'), (26, 17, 'Hip thrust barra'),
                                                           (27, 17, 'Hip thrusta disco'), (28, 18, 'Patada glúteos en polea'),
                                                           (29, 18, 'Patada glúteos en máquina'), (30, 19, 'Zancadas barra'),
                                                           (31, 19, 'Zancadas mancuernas'), (32, 22, 'Subidas al box lastradas'),
                                                           (33, 22, 'Salto al box'), (34, 23, 'Press mancuernas'),
                                                           (35, 25, 'Elevaciones frontales mancuerna'), (36, 25, 'Elevaciones frontales polea baja'),
                                                           (37, 25, 'Elevaciones frontales disco'), (38, 26, 'Elevaciones laterales mancuerna'),
                                                           (39, 26, 'Elevaciones laterales polea baja'), (40, 26, 'Elevaciones laterales máquina'),
                                                           (41, 29, 'Elevaciones posteriores mancuerna'), (42, 29, 'Elevaciones posteriores polea baja'),
                                                           (43, 29, 'Elevaciones posteriores maquina'), (44, 30, 'Curl bíceps barra'),
                                                           (45, 30, 'Curl bíceps mancuerna'), (46, 30, 'Curl bíceps polea baja'),
                                                           (47, 30, 'Curl bíceps máquina'), (48, 31, 'Curl scott mancuerna'),
                                                           (49, 32, 'Curl martillo polea baja'), (50, 33, 'Extensión tríceps máquina'),
                                                           (51, 33, 'Extensión tríceps disco'), (52, 33, 'Extensión tríceps mancuerna'),
                                                           (53, 33, 'Extensión tríceps polea alta'), (54, 34, 'Press francés barra Z'),
                                                           (55, 34, 'Press francés mancuerna'), (56, 36, 'Fondos en paralelas'),
                                                           (57, 36, 'Fondos entre bancos'), (58, 37, 'Plancha frontal'),
                                                           (59, 37, 'Plancha lateral');
