-- 1. Insert Muscle Groups
INSERT INTO muscle_groups (id, name, image) VALUES
                                                (1, 'Chest', 'https://drive.google.com/uc?id=1J4ZrnHY8Coi4Jqd_IKErNuxOKWn9yVO2'),
                                                (2, 'Back', 'https://drive.google.com/uc?id=1W7D7mdGuplJeru-0UzJGowO-RaJr4Xz7'),
                                                (3, 'Legs', 'https://drive.google.com/uc?id=1U9Ztw3MCVmDFnHMbJdP9qsIyTm00hzwf'),
                                                (4, 'Shoulder', 'https://drive.google.com/uc?id=1np00rXyMBjua5wXdofCMxFccPfaixEmQ'),
                                                (5, 'Arms', 'https://drive.google.com/uc?id=1BRK3udwDfBPl-IbXCy1m3cHHbhOuebVd'),
                                                (6, 'Core', 'https://drive.google.com/uc?id=1Ur8z6G8OJJQNFOTtzTz_yKQb9fD9YxKc');

-- 2. Insert Muscles
INSERT INTO muscles (id, muscle_group_id, name, image) VALUES
                                                    (1, 1, 'Pectoralis major', 'https://drive.google.com/uc?export=view&id=1kFK0jRo3MhpA7uwOeni6MCjg0mWrEJ1_'),
                                                    (2, 1, 'Pectoralis minor', 'https://drive.google.com/uc?export=view&id=1DNoTEzCg0uKMnodAnR1k83VCKXScKKnM'),
                                                    (3, 2, 'Latissimus dorsi', 'https://drive.google.com/uc?export=view&id=1nJq4z6XH-wOLO-b8_CIu1m-PYkipW_5S'),
                                                    (4, 2, 'Trapezius', 'https://drive.google.com/uc?export=view&id=1cbWve0TbchqNX-edQn895Q4ZFX7tzoxK'),
                                                    (5, 2, 'Spinal erectors (lumbar)', 'https://drive.google.com/uc?export=view&id=1gzoeC32cOclfmW9zyiBfNpJma-KEznuT'),
                                                    (6, 2, 'Teres major', 'https://drive.google.com/uc?export=view&id=1lYG-G0HkxqjXNRN_FW4u3qlbrw2GxHce'),
                                                    (7, 2, 'Serratus anterior', 'https://drive.google.com/uc?export=view&id=1ghAexWfCkhJhfUNhpiYs_MnMqAzZUcuA'),
                                                    (8, 2, 'Infraspinatus', 'https://drive.google.com/uc?export=view&id=1ThC2ON2TtIw3apQ_ove_x2qJc9GfWN83'),
                                                    (9, 2, 'Rhomboids', 'https://drive.google.com/uc?export=view&id=1zUkrH9L9gezs9XuKCtjyFfqJ3jBRpMnj'),
                                                    (10, 3, 'Quadriceps', 'https://drive.google.com/uc?export=view&id=1PlHSJFWZvYlOTyaPYcpEW4ijdQWIqM9N'),
                                                    (11, 3, 'Adductors', 'https://drive.google.com/uc?export=view&id=1KS09SgXoQ5DkDZT7N5NkTTZ7Q3clok7n'),
                                                    (12, 3, 'Abductors', 'https://drive.google.com/uc?export=view&id=1jPlis5Yr4pI31CLC6i-fwaTXINljOREG'),
                                                    (13, 3, 'Soleus', 'https://drive.google.com/uc?export=view&id=1TaAVae3bH-BCurnbdMS-AL1ytOxVkN5i'),
                                                    (14, 3, 'Hamstrings', 'https://drive.google.com/uc?export=view&id=1GXAPTjydO1CKcKoi9XI_G5b4LDElmQew'),
                                                    (15, 3, 'Gluteus maximus', 'https://drive.google.com/uc?export=view&id=1AO-O0BygznCZ8accconMbRTl1XuSjjWs'),
                                                    (16, 3, 'Gluteus medius', 'https://drive.google.com/uc?export=view&id=1Z2HIlmD0-c8G6mZ4dTVAMiR7R6i5dnnP'),
                                                    (17, 3, 'Tibialis anterior', 'https://drive.google.com/uc?export=view&id=1Fimil39uknDcUfFyoDzvQIGPf6lUpUu-'),
                                                    (18, 3, 'Gastrocnemius', 'https://drive.google.com/uc?export=view&id=1xUX3C1ddgYQhVwphEftEkK4XfhxJQ6M1'),
                                                    (19, 4, 'Anterior deltoid', 'https://drive.google.com/uc?export=view&id=1m5JwpqtoKYGuoi2k7AQ6SoNvbUBkqKra'),
                                                    (20, 4, 'Acromial deltoid', 'https://drive.google.com/uc?export=view&id=1wXd21j5XBAt41yZixMYw3RVEJCWwMi3s'),
                                                    (21, 4, 'Posterior deltoid', 'https://drive.google.com/uc?export=view&id=1OUXNnCPGZ8hoXSPUBN5e6Og4mj9AW163'),
                                                    (22, 5, 'Biceps brachii', 'https://drive.google.com/uc?export=view&id=1MaY9ewjNScna5PGPKuw1MJsyJxez9y9u'),
                                                    (23, 5, 'Triceps brachii', 'https://drive.google.com/uc?export=view&id=1qZq0Lmw55rezpjnGdkb8VdqmrCbz6OOr'),
                                                    (24, 5, 'Brachialis', 'https://drive.google.com/uc?export=view&id=1olEK63rn4Y7KY83IJNL00iNq6S3F68M3'),
                                                    (25, 5, 'Brachioradialis', 'https://drive.google.com/uc?export=view&id=1Z2oD54qvGgZp-ejmSPO6a5wQiZXzVitO'),
                                                    (26, 6, 'Rectus abdominis', 'https://drive.google.com/uc?export=view&id=1tNNVhAc8yQfm-W0M1IGEvyw_FP7BuW_6'),
                                                    (27, 6, 'Obliques', 'https://drive.google.com/uc?export=view&id=15m_x2NqTORZz7roYRHxJiVXfUeimxdCR'),
                                                    (28, 6, 'Transverse abdominis', 'https://drive.google.com/uc?export=view&id=1K30H5MoStwLDN92Rz3p_zECw00uvQXAe');

-- 3. Insert Base Exercises
INSERT INTO exercises (id, name, image , muscle_group_id) VALUES
                                                      (1, 'Bench Press', 'https://drive.google.com/uc?id=1nsGz08zBI4U6057Bk4DdYXJE4MoutVq2', 1),
                                                      (2, 'Incline Bench Press', 'https://drive.google.com/uc?id=1h-Kbj7owjoV1DtXD-pS8Dd1p1dvdhHI5', 1),
                                                      (3, 'Dumbbell Flyes', 'https://drive.usercontent.google.com/download?id=1vvHWOccDhsQQ7CjJiqED7xr45S_16-rJ&authuser=0', 1),
                                                      (4, 'Cable Crossovers', 'https://drive.google.com/uc?export=view&id=1n3Nd33ozn7GIQANycO4ZiEnRmuodnX2U', 1),
                                                      (5, 'Dumbbell Pullover', 'https://drive.usercontent.google.com/download?id=1v_-gMAnBW_h_QuTnHromBiUnMfWoaaOT&authuser=0', 1),
                                                      (6, 'Chest Dips', 'https://drive.google.com/uc?export=view&id=1Az4K1c7WWRNigBIiDJkl3M6SVoulUCe_', 1),
                                                      (7, 'Push-Ups', 'https://drive.google.com/uc?id=1HdVrOHC1bh8elb_anNp_5TJ1GEIYYHb2', 1),
                                                      (8, 'Deadlift', 'https://drive.google.com/uc?export=view&id=112h7bp0qsEqSdHRgpjcsUnLjzyhp2ZNa', 2),
                                                      (9, 'Barbell Row', 'https://drive.google.com/uc?export=view&id=17i8NxLS4OOZ_J5VxMgOs33LV8eY13ybj', 2),
                                                      (10, 'Seated Cable Row', 'https://drive.google.com/uc?export=view&id=1otpDB9uq4AEvXEdx5scCDhzEnh_rLYXN', 2),
                                                      (11, 'Pull-Ups', 'https://drive.google.com/uc?export=view&id=1lbHsqK-W_9g2NGrisUTwCQL1y7wyRxIf', 2),
                                                      (12, 'High Pulley Rows', 'https://drive.google.com/uc?export=view&id=1Hdby7e6BEdu4LURec2J7JzxjQwP-c6YS', 2),
                                                      (13, 'Shrugs', 'https://drive.google.com/uc?export=view&id=1lzQrnB2Lb46JrRp5r-ePGg7DgwkeFaik', 2),
                                                      (14, 'Squats', 'https://drive.google.com/uc?export=view&id=1mQhsDGHjZexOTh12tdqe_UFp0jRHU6TY', 3),
                                                      (15, 'Leg Extension', 'https://drive.google.com/uc?export=view&id=1lzQrnB2Lb46JrRp5r-ePGg7DgwkeFaik', 3),
                                                      (16, 'Leg Curl', 'https://drive.google.com/uc?export=view&id=1S6Xo3eqLkM05J4oe-ONzD1qoLMHhli0Y', 3),
                                                      (17, 'Hip Thrust', 'https://drive.google.com/uc?export=view&id=1Nll4jIvw2GuBDj0eX-rSEuB4hj2hTLEL', 3),
                                                      (18, 'Glute Kickback', 'https://drive.google.com/uc?export=view&id=1wc4Ewx9cGFKAPH9fCPu9tpMd84vpecEW', 3),
                                                      (19, 'Lunges', 'https://drive.google.com/uc?export=view&id=1jkw_RLyF2NhoV4K8bkukdZq6Fxz2rWmh', 3),
                                                      (20, 'Leg Press', 'https://drive.google.com/uc?export=view&id=171CcQ5J1PsuHM20o5v-w6RQEJBeTJx22', 3),
                                                      (21, 'Hack Squat', 'https://drive.google.com/uc?export=view&id=18PXjtfQ0KwOhtJms5d-55GckQ71Nh5Xy', 3),
                                                      (22, 'Box Step-Ups', 'https://drive.google.com/uc?export=view&id=16dHcu1W6kWBm9d_WYS6gffOWGlXNVzKB', 3),
                                                      (23, 'Overhead Press', 'https://drive.google.com/uc?export=view&id=1ImRj0l8O92mV84i7V0JN_mBKNWtpzWzp', 4),
                                                      (24, 'Arnold Press', 'https://drive.google.com/uc?export=view&id=10F_bwBC22RIIskZogddplbSocNYNkKYM', 4),
                                                      (25, 'Front Raises', 'https://drive.google.com/uc?export=view&id=13bEaZQYIBCx1kPdeCw3Qf3ApB2Ic-GdP',4),
                                                      (26, 'Lateral Raises', 'https://drive.google.com/uc?export=view&id=1451UI5oFQYFJs3fhQg5OrvDZ2ZqsRDKh', 4),
                                                      (27, 'Upright Row', 'https://drive.google.com/uc?export=view&id=1neWaCabM7UGKq0X7WceeN2SxRVcCQ4nd', 4),
                                                      (28, 'Shoulder Push-Up', 'https://drive.google.com/uc?export=view&id=1vvWEutbDRbaAfEgV7OrlvgJ_Y8_8294_', 4),
                                                      (29, 'Rear Delt Raises', 'https://drive.google.com/uc?export=view&id=1fg6Cf3AYiysoC00dPonwPWzBh46unAVU', 4),
                                                      (30, 'Biceps Curl', 'https://drive.google.com/uc?export=view&id=1v_2I0LtNzHt43WDuwnVTGANqGXVeLuWO ', 5),
                                                      (31, 'Scott Bench Curl', 'https://drive.google.com/uc?export=view&id=1zbQInNKY2hWDchYQ2pOFdEB_FxI_f6oQ', 5),
                                                      (32, 'Hammer Curl', 'https://drive.google.com/uc?export=view&id=1i3U7D5nqEO6nbKk_b9YCgXfUt6v9CX-B', 5),
                                                      (33, 'Triceps Extension', 'https://drive.google.com/uc?export=view&id=1wAYg9qCCr5mC_ISAGdT371yoVA6J7Vtt', 5),
                                                      (34, 'Skull Crushers', 'https://drive.google.com/uc?export=view&id=19qoMbyR4yoGhPpdFz5miMZ-S1mVScNcF', 5),
                                                      (35, 'Diamond Push-Ups', 'https://drive.google.com/uc?export=view&id=1jfOfKEgu-Hq2-J2__sSw1OJn-vGfY6O2', 5),
                                                      (36, 'Triceps Dips', 'https://drive.google.com/uc?export=view&id=1dyuvXHQNKeUcbczCInZBgmaiFXIjAY5o', 5),
                                                      (37, 'Plank', 'https://drive.google.com/uc?export=view&id=1FApWP7ACfBIFbiZvhNwCgSlvobBKhvNp', 6),
                                                      (38, 'Dead Bug', 'https://drive.google.com/uc?export=view&id=1UbuziCPOFKP9DVdKA1WD--TFY7gIZy5B', 6),
                                                      (39, 'Bird Dog', 'https://drive.google.com/uc?export=view&id=1xN2H6KH_XnAmGU0-UX8mk8-Ro0-CiLpR', 6),
                                                      (40, 'Mountain Climbers', 'https://drive.google.com/uc?export=view&id=12XmOgqIkjmadR47bnvaXvgIdQ6pvhQ9m', 6),
                                                      (41, 'Pallof Press', 'https://drive.google.com/uc?export=view&id=1Wu3ckZp6Ktbs4erQ7rrMgY_hPgFliM51', 6),
                                                      (42, 'Farmer’s Walk', 'https://drive.google.com/uc?export=view&id=1s0hH8WqrsPpOFOrL6jRfbtF3OlGBecvq', 6),
                                                      (43, 'Glute Bridge', 'https://drive.google.com/uc?export=view&id=13tmiweMF3WHR3kGBRW1LXaubah54Yx7_', 6),
                                                      (44, 'Back Extension', 'https://drive.google.com/uc?export=view&id=1jEtiEliBp-BP1aENCf7MDsny9clA1oRA', 6),
                                                      (45, 'Russian Twists', 'https://drive.google.com/uc?export=view&id=1WfCATCiHPQx9HqvspyAI1h7wJeFQJNvr', 6),
                                                      (46, 'Hollow Hold', 'https://drive.google.com/uc?export=view&id=1xwjk8oUxJxm_HlksOAgnInWu5QdCCc1H', 6);

-- 4. Insert Exercise-Muscle Relationships
INSERT INTO exercises_muscles (exercise_id, muscle_id, role) VALUES
                                                                 (1, 1, 'primary'), (1, 23, 'secondary'), (1, 20, 'secondary'),
                                                                 (2, 1, 'primary'), (2, 20, 'secondary'), (3, 1, 'primary'),
                                                                 (4, 1, 'primary'), (5, 1, 'secondary'), (5, 3, 'secondary'),
                                                                 (6, 1, 'primary'), (6, 23, 'secondary'), (7, 1, 'primary'), (7, 23, 'secondary'),
                                                                 (8, 5, 'primary'), (8, 15, 'primary'), (8, 14, 'secondary'),
                                                                 (9, 3, 'primary'), (9, 9, 'secondary'), (9, 4, 'secondary'), (9, 22, 'secondary'),
                                                                 (10, 3, 'primary'), (10, 9, 'secondary'), (10, 4, 'secondary'), (10, 22, 'secondary'),
                                                                 (11, 3, 'primary'), (11, 6, 'secondary'), (11, 22, 'secondary'), (11, 24, 'secondary'),
                                                                 (12, 3, 'primary'), (12, 6, 'secondary'), (12, 22, 'secondary'),
                                                                 (13, 4, 'primary'), (13, 5, 'stabilizer'),
                                                                 (14, 10, 'primary'), (14, 15, 'secondary'), (14, 14, 'secondary'), (14, 11, 'stabilizer'), (14, 16, 'stabilizer'),
                                                                 (15, 10, 'primary'), (16, 14, 'primary'),
                                                                 (17, 15, 'primary'), (17, 14, 'secondary'), (17, 16, 'secondary'),
                                                                 (18, 15, 'primary'), (18, 16, 'secondary'),
                                                                 (19, 10, 'primary'), (19, 15, 'secondary'), (19, 14, 'secondary'), (19, 16, 'stabilizer'),
                                                                 (20, 10, 'primary'), (20, 15, 'secondary'), (20, 14, 'secondary'),
                                                                 (21, 10, 'primary'), (21, 15, 'secondary'), (21, 14, 'secondary'),
                                                                 (22, 10, 'primary'), (22, 15, 'secondary'), (22, 14, 'secondary'), (22, 16, 'stabilizer'),
                                                                 (23, 19, 'primary'), (23, 20, 'secondary'), (23, 23, 'secondary'),
                                                                 (24, 19, 'primary'), (24, 20, 'secondary'), (24, 23, 'secondary'),
                                                                 (25, 19, 'primary'), (26, 20, 'primary'), (26, 4, 'secondary'),
                                                                 (27, 20, 'primary'), (27, 4, 'secondary'), (27, 22, 'secondary'),
                                                                 (28, 19, 'primary'), (29, 21, 'primary'), (29, 4, 'secondary'),
                                                                 (30, 22, 'primary'), (30, 24, 'secondary'), (30, 25, 'secondary'),
                                                                 (31, 22, 'primary'), (31, 24, 'secondary'),
                                                                 (32, 25, 'primary'), (32, 24, 'secondary'), (32, 22, 'secondary'),
                                                                 (33, 23, 'primary'), (34, 23, 'primary'),
                                                                 (35, 23, 'primary'), (35, 22, 'secondary'),
                                                                 (36, 23, 'primary'), (36, 22, 'secondary'),
                                                                 (37, 28, 'primary'), (37, 26, 'secondary'), (37, 27, 'secondary'),
                                                                 (38, 28, 'primary'), (38, 26, 'secondary'),
                                                                 (39, 5, 'secondary'), (39, 28, 'secondary'),
                                                                 (40, 26, 'primary'), (40, 27, 'secondary'),
                                                                 (41, 27, 'primary'), (41, 28, 'secondary'),
                                                                 (42, 28, 'primary'), (42, 27, 'secondary'),
                                                                 (43, 15, 'primary'), (43, 5, 'secondary'),
                                                                 (44, 5, 'primary'), (44, 15, 'secondary'),
                                                                 (45, 27, 'primary'), (45, 26, 'secondary'),
                                                                 (46, 26, 'primary'), (46, 28, 'secondary');

-- 5. Insert Exercise Variants
INSERT INTO exercises_variants (id, exercise_id, name) VALUES
                                                           (1, 1, 'Dumbbell Bench Press'),
                                                           (2, 2, 'Incline Dumbbell Bench Press'),
                                                           (3, 3, 'Incline Bench Flyes'),
                                                           (4, 3, 'Flat Bench Flyes'),
                                                           (5, 7, 'Plyometric Push-Ups'),
                                                           (6, 8, 'Sumo Deadlift'),
                                                           (7, 8, 'Dumbbell Deadlift'),
                                                           (8, 9, '3-Point Dumbbell Row'),
                                                           (9, 10, 'Single-Arm Cable Row'),
                                                           (10, 10, 'Wide-Grip Cable Row'),
                                                           (11, 10, 'Close-Grip Cable Row'),
                                                           (12, 11, 'Underhand Pull-Ups'),
                                                           (13, 11, 'Neutral-Grip Pull-Ups'),
                                                           (14, 11, 'Weighted Pull-Ups'),
                                                           (15, 12, 'Wide-Grip Lat Pulldown'),
                                                           (16, 12, 'Close-Grip Lat Pulldown'),
                                                           (17, 12, 'Single-Arm Lat Pulldown'),
                                                           (18, 13, 'Dumbbell Shrugs'),
                                                           (19, 14, 'Barbell Squat'),
                                                           (20, 14, 'Dumbbell Squat'),
                                                           (21, 14, 'Sumo Squat'),
                                                           (22, 14, 'Bulgarian Split Squat'),
                                                           (23, 16, 'Lying Leg Curl'),
                                                           (24, 16, 'Seated Leg Curl'),
                                                           (25, 17, 'Machine Hip Thrust'),
                                                           (26, 17, 'Barbell Hip Thrust'),
                                                           (27, 17, 'Plate Hip Thrust'),
                                                           (28, 18, 'Cable Glute Kickback'),
                                                           (29, 18, 'Machine Glute Kickback'),
                                                           (30, 19, 'Barbell Lunges'),
                                                           (31, 19, 'Dumbbell Lunges'),
                                                           (32, 22, 'Weighted Box Step-Ups'),
                                                           (33, 22, 'Box Jump'),
                                                           (34, 23, 'Dumbbell Shoulder Press'),
                                                           (35, 25, 'Dumbbell Front Raises'),
                                                           (36, 25, 'Low Cable Front Raises'),
                                                           (37, 25, 'Plate Front Raises'),
                                                           (38, 26, 'Dumbbell Lateral Raises'),
                                                           (39, 26, 'Low Cable Lateral Raises'),
                                                           (40, 26, 'Machine Lateral Raises'),
                                                           (41, 29, 'Dumbbell Rear Delt Raises'),
                                                           (42, 29, 'Low Cable Rear Delt Raises'),
                                                           (43, 29, 'Machine Rear Delt Raises'),
                                                           (44, 30, 'Barbell Biceps Curl'),
                                                           (45, 30, 'Dumbbell Biceps Curl'),
                                                           (46, 30, 'Low Cable Biceps Curl'),
                                                           (47, 30, 'Machine Biceps Curl'),
                                                           (48, 31, 'Dumbbell Preacher Curl'),
                                                           (49, 32, 'Low Cable Hammer Curl'),
                                                           (50, 33, 'Machine Triceps Extension'),
                                                           (51, 33, 'Plate Triceps Extension'),
                                                           (52, 33, 'Dumbbell Triceps Extension'),
                                                           (53, 33, 'High Cable Triceps Extension'),
                                                           (54, 34, 'EZ-Bar Skull Crusher'),
                                                           (55, 34, 'Dumbbell Skull Crusher'),
                                                           (56, 36, 'Parallel Bar Triceps Dips'),
                                                           (57, 36, 'Bench Triceps Dips'),
                                                           (58, 37, 'Front Plank'),
                                                           (59, 37, 'Side Plank');
-- 6. Insert Training goals
INSERT INTO training_goal (id, name, description) VALUES
                                                       (1, 'Hypertrophy', 'Objetivo centrado en ganar masa muscular mediante volumen e intensidad progresiva.'),
                                                       (2, 'Fat Loss', 'Entrenamiento orientado a perder grasa manteniendo la mayor masa muscular posible.'),
                                                       (3, 'Toning', 'Mejorar definición muscular y composición corporal.'),
                                                       (4, 'Strength', 'Incrementar la fuerza máxima usando cargas altas y descansos largos.'),
                                                       (5, 'Muscular Endurance', 'Mejorar la resistencia muscular con altas repeticiones y descansos cortos.'),
                                                       (6, 'General Fitness', 'Mejorar condición física general y salud.'),
                                                       (7, 'Specific Muscle Focus', 'Entrenamiento enfocado en desarrollar un grupo muscular concreto.');
-- 7. Insert Training methods
INSERT INTO training_method (id, name, description) VALUES
                                                         (1, 'Progressive Overload', 'Incrementar progresivamente la carga, volumen o dificultad del entrenamiento.'),
                                                         (2, 'RIR', 'Uso de repeticiones en reserva para controlar la intensidad del esfuerzo.'),
                                                         (3, 'RPE', 'Escala de percepción del esfuerzo para regular la intensidad.'),
                                                         (4, 'Superset', 'Realizar dos ejercicios consecutivos con poco o ningún descanso.'),
                                                         (5, 'Drop Set', 'Reducir el peso tras alcanzar el fallo y continuar la serie.'),
                                                         (6, 'Rest Pause', 'Pequeñas pausas dentro de una misma serie para extender el esfuerzo.'),
                                                         (7, 'Myo Reps', 'Mini series cortas tras una serie principal efectiva.'),
                                                         (8, 'Pyramid Set', 'Aumentar o disminuir progresivamente la carga entre series.'),
                                                         (9, 'Circuit Training', 'Ejercicios realizados consecutivamente para aumentar intensidad y gasto calórico.'),
                                                         (10, 'HIIT', 'Entrenamiento interválico de alta intensidad.'),
                                                         (11, 'Full Body', 'Entrenamiento de cuerpo completo en cada sesión.'),
                                                         (12, 'Push Pull Legs', 'División de entrenamiento por empuje, tirón y piernas.'),
                                                         (13, 'Upper Lower', 'División torso y pierna.'),
                                                         (14, 'Body Part Split', 'División clásica por grupos musculares.'),
                                                         (15, 'Time Under Tension', 'Control del tiempo de ejecución para aumentar estímulo muscular.'),
                                                         (16, 'Training to Failure', 'Series llevadas hasta el fallo muscular o muy cerca de él.');
-- 8. Insert Training methods
INSERT INTO training_level (id, name) VALUES
                                           (1, 'Beginner'),
                                           (2, 'Intermediate'),
                                           (3, 'Advanced');
-- 9. Insert Training methods
INSERT INTO work_split (id, name, description) VALUES
                                                       (1, 'Full Body', 'Trabajo de todo el cuerpo en cada sesión.'),
                                                       (2, 'Upper Lower', 'División torso y pierna.'),
                                                       (3, 'Push Pull Legs', 'División por empuje, tirón y piernas.'),
                                                       (4, 'Bro Split', 'Un grupo muscular principal por día.'),
                                                       (5, 'Hybrid', 'Combinación de distintos sistemas de entrenamiento.');

INSERT INTO work_plan
(id, name, description, days_per_week, duration_weeks, is_active, training_goal_id, training_level_id, work_split_id)
VALUES
    (1, 'PPL Hypertrophy Intermediate', 'Rutina Push Pull Legs enfocada en hipertrofia con volumen moderado-alto y sobrecarga progresiva.', 6, 12, 1, 1, 2, 3),
    (2, 'Full Body Fat Loss Beginner', 'Rutina Full Body para pérdida de grasa y mejora de condición física general.', 3, 8, 1, 2, 1, 1),
    (3, 'Upper Lower Strength Advanced', 'Programa torso-pierna orientado a fuerza máxima con cargas altas y descansos largos.', 4, 10, 1, 4, 3, 2),
    (4, 'Bro Split Hypertrophy Advanced', 'División clásica por grupos musculares enfocada en alto volumen de entrenamiento.', 5, 12, 1, 1, 3, 4),
    (5, 'Full Body General Fitness Beginner', 'Rutina equilibrada para mejorar salud, movilidad, fuerza básica y condición física general.', 3, 6, 1, 6, 1, 1),
    (6, 'Glute Focus Intermediate', 'Programa específico para desarrollo de glúteos y piernas con énfasis en hipertrofia.', 4, 10, 1, 7, 2, 2);
